-- MySQL Script generated by MySQL Workbench
-- Wed Aug 26 15:48:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio_MVC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolio_MVC` ;

-- -----------------------------------------------------
-- Schema portfolio_MVC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio_MVC` DEFAULT CHARACTER SET utf8 ;
USE `portfolio_MVC` ;

-- -----------------------------------------------------
-- Table `portfolio_MVC`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_MVC`.`projects` ;

CREATE TABLE IF NOT EXISTS `portfolio_MVC`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `images` VARCHAR(200) NOT NULL,
  `categories` VARCHAR(200) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_MVC`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_MVC`.`authors` ;

CREATE TABLE IF NOT EXISTS `portfolio_MVC`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `about_id` INT NOT NULL,
  PRIMARY KEY (`id`, `about_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_MVC`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_MVC`.`articles` ;

CREATE TABLE IF NOT EXISTS `portfolio_MVC`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `images` VARCHAR(200) NOT NULL,
  `categories` VARCHAR(200) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_MVC`.`authors_has_articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_MVC`.`authors_has_articles` ;

CREATE TABLE IF NOT EXISTS `portfolio_MVC`.`authors_has_articles` (
  `authors_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  PRIMARY KEY (`authors_id`, `articles_id`),
  CONSTRAINT `fk_authors_has_articles_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `portfolio_MVC`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authors_has_articles_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `portfolio_MVC`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_authors_has_articles_articles1_idx` ON `portfolio_MVC`.`authors_has_articles` (`articles_id` ASC) VISIBLE;

CREATE INDEX `fk_authors_has_articles_authors1_idx` ON `portfolio_MVC`.`authors_has_articles` (`authors_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_MVC`.`about`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_MVC`.`about` ;

CREATE TABLE IF NOT EXISTS `portfolio_MVC`.`about` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `text` TEXT(500) NOT NULL,
  `images` VARCHAR(200) NULL,
  `authors_id` INT NOT NULL,
  `authors_about_id` INT NOT NULL,
  PRIMARY KEY (`id`, `authors_id`, `authors_about_id`),
  CONSTRAINT `fk_about_authors1`
    FOREIGN KEY (`authors_id` , `authors_about_id`)
    REFERENCES `portfolio_MVC`.`authors` (`id` , `about_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_about_authors1_idx` ON `portfolio_MVC`.`about` (`authors_id` ASC, `authors_about_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_MVC`.`authors_has_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_MVC`.`authors_has_projects` ;

CREATE TABLE IF NOT EXISTS `portfolio_MVC`.`authors_has_projects` (
  `authors_id` INT NOT NULL,
  `authors_about_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`authors_id`, `authors_about_id`, `projects_id`),
  CONSTRAINT `fk_authors_has_projects_authors1`
    FOREIGN KEY (`authors_id` , `authors_about_id`)
    REFERENCES `portfolio_MVC`.`authors` (`id` , `about_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authors_has_projects_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `portfolio_MVC`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_authors_has_projects_projects1_idx` ON `portfolio_MVC`.`authors_has_projects` (`projects_id` ASC) VISIBLE;

CREATE INDEX `fk_authors_has_projects_authors1_idx` ON `portfolio_MVC`.`authors_has_projects` (`authors_id` ASC, `authors_about_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
